arch:
  [
    "cortex-m0",
    "cortex-m0plus",
    "cortex-m1",
    "cortex-m3",
    "cortex-m4+nofp",
    "cortex-m4",
    "cortex-m7",
    "cortex-m23",
    "cortex-m33",
    "cortex-m35p",
    "cortex-m55",
    "cortex-m85",
  ]
