arch:
  [
    "cortex-m0",
    "cortex-m0plus",
    "cortex-m1",
    "cortex-m3",
    "cortex-m4",
    "cortex-m4f",
    "cortex-m7",
    "cortex-m7f",
    "cortex-m7d",
    "cortex-m23",
    "cortex-m33",
    "cortex-m33f",
    "cortex-m33p",
    "cortex-m35pf",
    "cortex-m55",
    "cortex-m85",
  ]
compiler:
  gcc:
    # libc to be linked to the binary with baremetal OS
    # Must NOT be specified for building libraries
    # ANY allows additional libc variants
    newlib: [null, nano, nosys, linux, nano_nosys, picolibc, ANY]
